/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.pdrc.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author rufino
 */
@StyleSheet
@Template(CrudFormPage.class)
public class EditDetaineePage extends javax.swing.JPanel {

    /**
     * Creates new form NewDetaineePage
     */
    public EditDetaineePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        xPanel5 = new com.rameses.rcp.control.XPanel();
        xDataTable6 = new com.rameses.rcp.control.XDataTable();
        xFormPanel9 = new com.rameses.rcp.control.XFormPanel();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xHorizontalPanel2 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        entityAddress2 = new com.rameses.enterprise.components.EntityAddress();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xFormPanel8 = new com.rameses.rcp.control.XFormPanel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xDateField4 = new com.rameses.rcp.control.XDateField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xDateField5 = new com.rameses.rcp.control.XDateField();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();
        xDataTable3 = new com.rameses.rcp.control.XDataTable();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xDataTable4 = new com.rameses.rcp.control.XDataTable();
        xPanel3 = new com.rameses.rcp.control.XPanel();
        xDataTable5 = new com.rameses.rcp.control.XDataTable();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xHorizontalPanel1 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xFormPanel7 = new com.rameses.rcp.control.XFormPanel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xPanel4 = new com.rameses.rcp.control.XPanel();
        xPhoto2 = new com.rameses.rcp.control.XPhoto();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(25, 10, 10, 10));
        xTitledBorder1.setTitle("Detainee Details");
        jPanel1.setBorder(xTitledBorder1);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Language and Dialect");
        xDataTable6.setBorder(xTitledBorder2);
        xDataTable6.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "name"}
                , new Object[]{"caption", "Name"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable6.setHandler("listHandlerLanguage");
        xDataTable6.setName("selectedLanguage"); // NOI18N

        xTextField12.setCaption("Organization");
        xTextField12.setCaptionWidth(120);
        xTextField12.setName("entity.detainee.organization"); // NOI18N
        xTextField12.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel9.add(xTextField12);

        javax.swing.GroupLayout xPanel5Layout = new javax.swing.GroupLayout(xPanel5);
        xPanel5.setLayout(xPanel5Layout);
        xPanel5Layout.setHorizontalGroup(
            xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xDataTable6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(834, Short.MAX_VALUE))
        );
        xPanel5Layout.setVerticalGroup(
            xPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Social", xPanel5);

        xTextField8.setCaption("Attainment");
        xTextField8.setName("entity.detainee.attainment"); // NOI18N
        xTextField8.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel4.add(xTextField8);

        jTabbedPane1.addTab("Education", xFormPanel4);

        xHorizontalPanel2.setPreferredSize(new java.awt.Dimension(1000, 100));

        xFormPanel6.setPreferredSize(new java.awt.Dimension(500, 470));

        entityAddress2.setCaption("Place of Arrest");
        entityAddress2.setCaptionWidth(120);
        entityAddress2.setName("entity.detainee.placeofarrest"); // NOI18N
        entityAddress2.setPreferredSize(new java.awt.Dimension(0, 86));
        entityAddress2.setRequired(true);
        xFormPanel6.add(entityAddress2);

        xDateField1.setCaption("Date of Arrest");
        xDateField1.setCaptionWidth(120);
        xDateField1.setName("entity.detainee.dateofarrest"); // NOI18N
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xDateField1.setRequired(true);
        xFormPanel6.add(xDateField1);

        xTextField10.setCaption("Time of Arrest");
        xTextField10.setCaptionWidth(120);
        xTextField10.setHint("HH:MM AM");
        xTextField10.setName("entity.detainee.timeofarrest"); // NOI18N
        xTextField10.setRequired(true);
        xFormPanel6.add(xTextField10);

        xTextField11.setCaption("Arresting Official");
        xTextField11.setCaptionWidth(120);
        xTextField11.setName("entity.detainee.arrestingofficial"); // NOI18N
        xTextField11.setPreferredSize(new java.awt.Dimension(300, 20));
        xTextField11.setRequired(true);
        xFormPanel6.add(xTextField11);

        xLookupField1.setText("#{item.name} ");
        xLookupField1.setCaption("Court Branch");
        xLookupField1.setCaptionWidth(120);
        xLookupField1.setExpression("#{item.name} ");
        xLookupField1.setHandler("lookupCourts");
        xLookupField1.setName("entity.detainee.courtbranch"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel6.add(xLookupField1);

        xDateField2.setCaption("Date of Commitment");
        xDateField2.setCaptionFontStyle("");
        xDateField2.setCaptionWidth(120);
        xDateField2.setName("entity.detainee.dateofcommitment"); // NOI18N
        xFormPanel6.add(xDateField2);

        xDateField3.setCaption("Date of Sentence ");
        xDateField3.setCaptionFontStyle("");
        xDateField3.setCaptionWidth(120);
        xDateField3.setName("entity.detainee.dateofsentence"); // NOI18N
        xFormPanel6.add(xDateField3);

        xIntegerField1.setCaption("Serving Sentence");
        xIntegerField1.setCaptionWidth(120);
        xIntegerField1.setName("entity.detainee.sentence"); // NOI18N
        xFormPanel6.add(xIntegerField1);

        xHorizontalPanel2.add(xFormPanel6);

        xFormPanel8.setPreferredSize(new java.awt.Dimension(500, 100));

        xLookupField2.setCaption("Cell");
        xLookupField2.setCaptionWidth(120);
        xLookupField2.setExpression("#{item.name} ");
        xLookupField2.setHandler("lookupCells");
        xLookupField2.setName("entity.detainee.cell"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel8.add(xLookupField2);

        xCheckBox1.setCaption("");
        xCheckBox1.setCaptionWidth(120);
        xCheckBox1.setName("entity.detainee.ismental"); // NOI18N
        xCheckBox1.setText("With Mental");
        xFormPanel8.add(xCheckBox1);

        xDateField4.setCaption("Date Released");
        xDateField4.setCaptionWidth(120);
        xDateField4.setName("entity.detainee.daterelease"); // NOI18N
        xFormPanel8.add(xDateField4);

        xIntegerField2.setText("xIntegerField2");
        xIntegerField2.setCaption("Type");
        xIntegerField2.setCaptionWidth(120);
        xFormPanel8.add(xIntegerField2);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 63));

        xTextArea1.setCaption("Remarks");
        xTextArea1.setCaptionWidth(120);
        xTextArea1.setName("entity.detaine.remarks"); // NOI18N
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel8.add(jScrollPane1);

        xLookupField3.setCaption("Cause of Dropping");
        xLookupField3.setCaptionWidth(120);
        xLookupField3.setExpression("#{item.name} ");
        xLookupField3.setHandler("lookupCauseOfDropping");
        xLookupField3.setName("entity.detainee.causeofdropping"); // NOI18N
        xLookupField3.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel8.add(xLookupField3);

        xCheckBox2.setCaption("");
        xCheckBox2.setCaptionWidth(120);
        xCheckBox2.setName("entity.detainee.istransfered"); // NOI18N
        xCheckBox2.setText("Transfered");
        xFormPanel8.add(xCheckBox2);

        xDateField5.setCaption("Date of Transfer");
        xDateField5.setCaptionWidth(120);
        xDateField5.setName("entity.detainee.dateoftransfer"); // NOI18N
        xFormPanel8.add(xDateField5);

        xHorizontalPanel2.add(xFormPanel8);

        jTabbedPane1.addTab("ArrestDetail", xHorizontalPanel2);

        xTextField9.setCaption("Occupation");
        xTextField9.setName("entity.detainee.occupation"); // NOI18N
        xTextField9.setPreferredSize(new java.awt.Dimension(300, 20));
        xFormPanel5.add(xTextField9);

        jTabbedPane1.addTab("Economic", xFormPanel5);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Cases List");
        xDataTable2.setBorder(xTitledBorder3);
        xDataTable2.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "courtcase"}
                , new Object[]{"caption", "Case"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.LookupColumnHandler("#{item.courtcase.name}", "lookupCases")}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "court"}
                , new Object[]{"caption", "Court Branch"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.LookupColumnHandler("#{item.court.name}", "lookupCourts1")}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "releaseremarks"}
                , new Object[]{"caption", "Release Remarks"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "caseremarks"}
                , new Object[]{"caption", "Case Remarks"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "sentencedate"}
                , new Object[]{"caption", "Sentence Date"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DateColumnHandler(null, null, null)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "sentence"}
                , new Object[]{"caption", "Sentence"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable2.setHandler("listHandlerCases");
        xDataTable2.setName("selectedCase"); // NOI18N

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Councel List");
        xDataTable3.setBorder(xTitledBorder4);
        xDataTable3.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "counsel"}
                , new Object[]{"caption", "Counsel Name"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.LookupColumnHandler("#{item.counsel.name}", "lookupCounsels")}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "type"}
                , new Object[]{"caption", "Type"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.ComboBoxColumnHandler("counseltypes", null, null)}
            })
        });
        xDataTable3.setDepends(new String[] {"selectedCase"});
        xDataTable3.setDynamic(true);
        xDataTable3.setHandler("listHandlerCounsels");
        xDataTable3.setName("selectedCounsel"); // NOI18N

        javax.swing.GroupLayout xPanel1Layout = new javax.swing.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xDataTable2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
            .addComponent(xDataTable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xDataTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cases", xPanel1);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder5 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder5.setTitle("Cell List");
        xDataTable4.setBorder(xTitledBorder5);
        xDataTable4.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "cell"}
                , new Object[]{"caption", "Name"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.LookupColumnHandler("#{item.cell.name}", "lookupCells")}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "date"}
                , new Object[]{"caption", "Date"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DateColumnHandler(null, null, null)}
            })
        });
        xDataTable4.setHandler("listHandlerCells");
        xDataTable4.setName("selectedCell"); // NOI18N

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable4, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                .addContainerGap())
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable4, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cell", xPanel2);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder6 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder6.setTitle("Contact List");
        xDataTable5.setBorder(xTitledBorder6);
        xDataTable5.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "name"}
                , new Object[]{"caption", "Name"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.LookupColumnHandler("#{item.name}", "lookupContacts")}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "address"}
                , new Object[]{"caption", "Address"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"expression", "#{item.contact.addresstext}"}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "relationship"}
                , new Object[]{"caption", "Relationship"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.NONE}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.LookupColumnHandler("#{item.relationship.name}", "lookupRelationship")}
            })
        });
        xDataTable5.setHandler("listHandlerContacts");
        xDataTable5.setName("selectedContact"); // NOI18N

        javax.swing.GroupLayout xPanel3Layout = new javax.swing.GroupLayout(xPanel3);
        xPanel3.setLayout(xPanel3Layout);
        xPanel3Layout.setHorizontalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable5, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                .addContainerGap())
        );
        xPanel3Layout.setVerticalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xDataTable5, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contacts", xPanel3);

        xTextField2.setCaption("Height (Ft)");
        xTextField2.setName("entity.heightft"); // NOI18N
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xTextField3.setCaption("Weight (Kg)");
        xTextField3.setName("entity.weightkg"); // NOI18N
        xTextField3.setRequired(true);
        xFormPanel1.add(xTextField3);

        xComboBox2.setCaption("Eye Color");
        xComboBox2.setItems("colors");
        xComboBox2.setName("entity.eyecolor"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(100, 20));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xComboBox3.setCaption("Hair Color");
        xComboBox3.setItems("colors");
        xComboBox3.setName("entity.haircolor"); // NOI18N
        xComboBox3.setPreferredSize(new java.awt.Dimension(100, 20));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        xComboBox1.setCaption("Build");
        xComboBox1.setItems("bodybuild");
        xComboBox1.setName("entity.bodybuild"); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 20));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xComboBox4.setCaption("Complexion");
        xComboBox4.setItems("complexion");
        xComboBox4.setName("entity.complexion"); // NOI18N
        xComboBox4.setPreferredSize(new java.awt.Dimension(100, 20));
        xComboBox4.setRequired(true);
        xFormPanel1.add(xComboBox4);

        xTextField4.setCaption("Scars & Marks");
        xTextField4.setName("entity.scarsandmarks"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xTextField4);

        xTextField7.setCaption("Peculiarities");
        xTextField7.setName("entity.peculiarities"); // NOI18N
        xTextField7.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xTextField7);

        jTabbedPane1.addTab("Physical", xFormPanel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder7 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder7.setPadding(new java.awt.Insets(25, 10, 10, 10));
        xTitledBorder7.setTitle("Detainee Personal Information");
        xHorizontalPanel1.setBorder(xTitledBorder7);
        xHorizontalPanel1.setPreferredSize(new java.awt.Dimension(1000, 300));

        xFormPanel2.setPreferredSize(new java.awt.Dimension(500, 100));

        entityLookup1.setCaption("Detainee");
        entityLookup1.setCaptionWidth(120);
        entityLookup1.setName("entity"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        entityLookup1.setRequired(true);
        xFormPanel2.add(entityLookup1);

        xTextField1.setCaption("Alias");
        xTextField1.setCaptionWidth(120);
        xTextField1.setName("entity.alias"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(300, 20));
        xTextField1.setRequired(true);
        xFormPanel2.add(xTextField1);

        xHorizontalPanel1.add(xFormPanel2);

        xFormPanel7.setPreferredSize(new java.awt.Dimension(500, 100));

        xLabel7.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel7.setCaption("Created By");
        xLabel7.setExpression("#{entity.recordlog.createdbyuser}");
        xLabel7.setFor("");
        xLabel7.setName(""); // NOI18N
        xLabel7.setOpaque(true);
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel7.add(xLabel7);

        xLabel4.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel4.setCaption("Date Created");
        xLabel4.setExpression("#{entity.recordlog.datecreated}");
        xLabel4.setFor("");
        xLabel4.setOpaque(true);
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel7.add(xLabel4);

        xLabel5.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel5.setCaption("Prison No.");
        xLabel5.setExpression("#{entity.recordlog.datecreated}");
        xLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        xLabel5.setFor("");
        xLabel5.setForeground(new java.awt.Color(204, 0, 0));
        xLabel5.setName("entity.detainee.prisonno"); // NOI18N
        xLabel5.setOpaque(true);
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 50));
        xFormPanel7.add(xLabel5);

        xHorizontalPanel1.add(xFormPanel7);

        xPhoto2.setDepends(new String[] {"entity.detainee"});
        xPhoto2.setName("entity.detainee.photo"); // NOI18N
        xPhoto2.setText("xPhoto2");

        javax.swing.GroupLayout xPanel4Layout = new javax.swing.GroupLayout(xPanel4);
        xPanel4.setLayout(xPanel4Layout);
        xPanel4Layout.setHorizontalGroup(
            xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xPhoto2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );
        xPanel4Layout.setVerticalGroup(
            xPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xPhoto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        xHorizontalPanel1.add(xPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xHorizontalPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xHorizontalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.EntityAddress entityAddress2;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XDataTable xDataTable3;
    private com.rameses.rcp.control.XDataTable xDataTable4;
    private com.rameses.rcp.control.XDataTable xDataTable5;
    private com.rameses.rcp.control.XDataTable xDataTable6;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XFormPanel xFormPanel7;
    private com.rameses.rcp.control.XFormPanel xFormPanel8;
    private com.rameses.rcp.control.XFormPanel xFormPanel9;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel1;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XPanel xPanel3;
    private com.rameses.rcp.control.XPanel xPanel4;
    private com.rameses.rcp.control.XPanel xPanel5;
    private com.rameses.rcp.control.XPhoto xPhoto2;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
